<?php
return array(
  "transport_types" => ['老师邮寄','学生退货'],
  "demand_types" => ["资料","答疑","授课"],
  "demand_require_identity" => ["不限","老师","机构","学长"],
  "demand_require_authenticate" => ["不限","实名认证"],
  "demand_require_security" => ["不限","信誉保证"],
  "service_types" => ["资料","答疑","授课","直播课"],
  "service_require_identity" => ["不限","老师","机构","学长"],
  "service_require_authenticate" => ["不限","实名认证"],
  "service_require_security" => ["不限","信誉保证"],
  "3types" => ["非统考","统考","公共课"],
  "school" => ["type" => ["城市","学校","学院","专业"]],
  "mj_major" => ["mj_type" => ["学科门类","一级学科"]],
  "feeling_status" => ["单身","求交往","暗恋中","暧昧中","恋爱中","订婚","已婚"],
  "mb_profile_status" => ["等待审核","审核通过","被拒绝"],
  "mb_member_realname_status" => ["未提交审核","等待审核","审核通过","被拒绝"],
  "cart_object_type" => ["服务"],
  "order_status"=>["没付款","已付款","已发货","已收货","已评价","已申请退款","已同意退款","学生申请退款","老师同意退款","学生退货已发出","老师已收到退货，交易结束","老师拒绝退货，如有异议请申请仲裁"],
  "order_refund_reason" => ['与情况不符','买重了','其他'],
  "attachment_type"=>["说说","资讯",'服务'],
  "comment_type" => ["公开课","服务","需求","说说","资讯","分享","活动"],
  "activity_types" => ["学术","社团","兴趣交友","企业招聘","商业","同城","其他"],
  "question" => ["你父母的名字","你的爱好","你的启蒙老师","不知道类型"],
  
  "information_types" => ["院校动态","资讯","公告","下载","yy直播","网络课程"],
  "information0_types" => ["政策新闻","考研护航（初试）","考研护航（复试）","考研心得","就业职场","研究生圈"],
  "information_gonggao_types" => ["本站公告","关于我们","联系我们"],
  "collection_types" => ["公开课","资讯"],
  "bankcard_types" => ["中国银行","中国建设银行","中国工商银行","中国农业银行","中国邮政储蓄银行","交通银行","招商银行"],
  "tixian_types" => ['待审核','通过','被拒绝'],
  "recharge_types" => ['未付款','已付款','付款失败'],
  "apply_status" => ['已申请','已同意'],
  "member_post_view_permissions" => ["所有人可见",'对自己可见',],
  "service_order_status" => ['未付款','已付款'] ,
  "plan_stauts" => ['待确认','已同意','被取消','申诉'],
  "learning_period_status" => ['正在上课','已结束','已终止'],
  'cash_types' => ['','充值','提现',''],
  "cash_pay_types" => ['微信','支付宝','银行卡'],
  "payment_record_types" => ['','提现','充值','托付费用','直播课','资料','答疑授课','有偿问答','偷听答案','退款','管理费','解冻托付费用','资讯下载','分享下载'],
  'payment_record_income_types' => ['内','外'],
  'message_types' => ['系统通知','试听','协议','学习管理','评价','投标','支付','仲裁','网站广播','直播课','匹配专业推荐'],
  'essay_types' => ['需求','服务'],
  'circle_member_tyeps' => ['圈主','普通成员'],
 'member_post_types' => ["全部","公告","热门","名师","粉丝","关注","自己"],
 'member_types' => ['研友','老师'],
  'audition_status' => ["申请中..","已同意","删除","取消","不通过"],
  'validates' => [
    'service' => [
      ['description','require','必须要描述'],
      ['image','require','必须要图片']
    ],
  ],
);

